# Generated by Django 5.2.8 on 2026-01-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_alter_message_text'),
        ('teams', '0009_alter_team_plan_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='team_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.team'),
        ),
    ]
