# Generated by Django 5.2.8 on 2026-01-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_team_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='team_pk',
            new_name='team',
        ),
    ]
