# Generated by Django 5.2.8 on 2026-01-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_team_pk_message_team'),
        ('teams', '0009_alter_team_plan_delete_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('team_id__isnull', False), ('receiver_id__isnull', False), _connector='OR'), name='null_receiver_only_if_team_exists'),
        ),
    ]
