# Generated by Django 5.2.8 on 2025-11-27 16:46

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('teams', '0006_plan_max_orders_plan_max_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='products_Product_status_Status',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('DRAFT', 'Draft'), ('OUT_OF_STOCK', 'Out of Stock'), ('ARCHIVED', 'Archived'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'OUT_OF_STOCK', 'ARCHIVED', 'ACTIVE', 'INACTIVE'])), name='products_Product_status_Status'),
        ),
    ]
