# Generated by Django 5.2.8 on 2025-11-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('leads', '0002_lead_converted_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
    ]
