# Generated by Django 5.2.8 on 2025-11-20 18:06

from django.db import migrations, models

from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
