# Generated by Django 5.2.8 on 2025-12-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('teams', '0007_plan_max_order_items'),
    ]

    operations = [
        
    ]
