# Generated by Django 5.2.8 on 2025-12-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
        ('teams', '0008_alter_team_plan_delete_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='plans.plan'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
