# Generated by Django 5.2.8 on 2025-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_orders',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='max_products',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
