# Generated by Django 5.2.8 on 2025-11-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_plan_max_orders_plan_max_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_order_items',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
