# Generated by Django 5.2.8 on 2025-12-10 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=1024, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
