# Generated by Django 5.2.8 on 2025-11-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',)},
        ),
    ]
