# Generated by Django 5.2.8 on 2025-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_read_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('is_read', 'updated_at')},
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='fd', max_length=63),
            preserve_default=False,
        ),
    ]
