# Generated by Django 5.2.8 on 2025-12-22 13:30

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_title'),
        ('teams', '0009_alter_team_plan_delete_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(choices=[('NOT_READ', 'Not read'), ('READ', 'Read'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='NOT_READ', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('NOT_READ', 'Not read'), ('READ', 'Read'), ('HIDDEN', 'Hidden'), ('DELETED', 'Deleted'), ('FAILED', 'Failed')], default='NOT_READ', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['NOT_READ', 'READ', 'HIDDEN', 'DELETED', 'FAILED'])), name='notifications_Notification_status_Status'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team'),
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['NOT_READ', 'READ', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELED'])), name='notifications_TeamInvitation_status_Status'),
        ),
    ]
