# Generated by Django 5.2.8 on 2025-12-26 15:45

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_teaminvitation_receiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('content', models.TextField(blank=True)),
                ('status', django_enum.fields.EnumCharField(choices=[('NOT_READ', 'Not read'), ('READ', 'Read'), ('HIDDEN', 'Hidden'), ('DELETED', 'Deleted'), ('FAILED', 'Failed')], default='NOT_READ', max_length=8)),
                ('is_read', models.BooleanField()),
                ('read_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_read', 'updated_at'),
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['NOT_READ', 'READ', 'HIDDEN', 'DELETED', 'FAILED'])), name='notifications_Message_status_Status'),
        ),
    ]
