# Generated by Django 5.2.8 on 2025-11-18 18:50

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(10, 'Low'), (20, 'Medium'), (30, 'High')], default=20)),
                ('status', django_enum.fields.EnumCharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__in', [10, 20, 30])), name='leads_Lead_priority_Priority'), models.CheckConstraint(condition=models.Q(('status__in', ['NEW', 'CONTACTED', 'WON', 'LOST'])), name='leads_Lead_status_Status')],
            },
        ),
    ]
