# Generated by Django 5.2.8 on 2025-11-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('name',)},
        ),
    ]
