# Generated by Django 5.2.8 on 2025-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfile',
            name='is_image',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadfile',
            name='file',
            field=models.FileField(upload_to='lead_files'),
        ),
    ]
